names=-@,ref
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ryNQ5k/src/refm/api/src/dl/dl2/CPtr

--- ref   -> DL::CPtr
--- -@    -> DL::CPtr

自身を指す CPtr オブジェクトを返します。
C 言語におけるポインタへのアドレス演算子の適用 &p と同じです。

この返り値には、free 関数がセットされていません。

例:

 require 'dl/import'
 
 s = 'abc'
 cptr = DL::CPtr[s]
 cref = cptr.ref
 p cref.to_s(4).unpack('l*')[0]  #=> 136121648
 p cptr.to_i                     #=> 136121648
 p cref.ptr.to_s                 #=> "abc"


