names=-
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ryNQ5k/src/refm/api/src/dl/dl2/CPtr

--- -(n)   -> DL::CPtr

自身のアドレスから n バイトを引いた新しい CPtr オブジェクトを返します。

この返り値には、free 関数がセットされていません。

@param n アドレスの差分を整数で指定します。

例:
 require 'dl' 
 
 s = 'abc'
 cptr = DL::CPtr[s]
 cptr += 1
 p cptr[0,1]         #=> "b"
 cptr -= 1
 p cptr[0,1]         #=> "a"

