names=type_params
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:1784

--- type_params -> Hash
Content-Type のパラメータを {"charset" => "iso-2022-jp"}
という形の [[c:Hash]] で返します。

Content-Type: ヘッダフィールドが存在しない場合には
空のハッシュを返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
res = Net::HTTP.get_response(uri)
res.type_params # => {"charset"=>"UTF-8"}
//}

