names=body
visibility=public
kind=defined

--- body -> String
サーバに送るリクエストのエンティティボディを返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Post.new(uri.request_uri)
req.body = "Test Post Data"
req.body # => "Test Post Data"
//}

@see [[m:Net::HTTPGenericRequest#body=]]

