names=path
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPRequest:84

--- path -> String

リクエストする path を文字列で返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Get.new(uri.request_uri)
req.path # => "/index.html"
//}

