names=request_body_permitted?
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPRequest:96

--- request_body_permitted? -> bool

リクエストにエンティティボディを一緒に送ることが許されている
HTTP メソッド (POST など)の場合真を返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
post = Net::HTTP::Post.new(uri.request_uri)
post.request_body_permitted?   # => true

head = Net::HTTP::Head.new(uri.request_uri)
head.request_body_permitted?   # => false
//}

