names=[],sym
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ZtgaSH/src/refm/api/src/dl/dl2/Handle

--- sym(func) -> Integer
--- [](func) -> Integer

ライブラリのデフォルトの検索順序に従い、現在のライブラリ以降の
シンボルを探します。

DL::Handle::NEXT.sym(func) と同じです。詳しくは [[man:dlsym(3)]] の
RTLD_NEXT を見てください。

@raise DL::DLError シンボルが見つからなかった時に発生します。

