names=content_type=,set_content_type
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:1738

--- content_type=(type)
--- set_content_type(type, params = {})
type と params から Content-Type: ヘッダフィールドの
値を設定します。

@param type メディアタイプを文字列で指定します。
@param params パラメータ属性をハッシュで指定します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Get.new(uri.request_uri)
req.content_type                          # => nil
req.content_type = 'multipart/form-data'  # => "multipart/form-data"
req.content_type                          # => "multipart/form-data"
//}

