names=cert_store=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def cert_store=(store)

接続相手の証明書の検証のために使う、信頼している CA 証明書を含む証明書ストアを設定します。

通常は [m:Net::HTTP#ca_file=] や [m:Net::HTTP#ca_path=] で設定しますが、より詳細な設定をしたい場合にはこちらを用います。

デフォルトは nil (証明書ストアを指定しない)です。

- **SEE** [m:Net::HTTP#cert_store=], [m:OpenSSL::SSL::SSLContext#cert_store]

