names=close_on_empty_response
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def close_on_empty_response -> bool

レスポンスがボディを持っていない場合にコネクションを
閉じるかどうかを返します。

デフォルトでは偽(閉じない)です。

- **SEE** [m:Net::HTTP#close_on_empty_response=]

