names=proxy_from_env=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_from_env=3d=2.0.0
until_by_name=

### def proxy_from_env=(boolean)

プロクシ情報を環境変数から得るかどうかを指定します。

[m:Net::HTTP#start] で接続する前に設定する必要があります。

- **param** `boolean` -- プロクシ情報を環境変数から得るかどうかを指定する真偽値

- **SEE** [m:Net::HTTP#proxy_from_env?] 

