names=proxy_use_ssl=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_use_ssl=3d=3.4
until_by_name=
rbs_sig=(uninitialized)

### def proxy_use_ssl=(ssl)

プロクシとの接続(プロクシ自身への TCP 接続)に SSL/TLS を使うかどうかを設定します。[m:Net::HTTP#start] で接続する前に設定する必要があります。

これは、プロクシ経由で接続先自体に SSL/TLS を使うかどうかを指定する [m:Net::HTTP#use_ssl=] とは別の設定です。

- **param** `ssl` -- プロクシとの接続に SSL/TLS を使うかどうかを真偽値で指定します。

```ruby title="例"
require 'net/http'

http = Net::HTTP.new('www.example.com')
http.proxy_use_ssl = true
```

- **SEE** [m:Net::HTTP.proxy_use_ssl], [m:Net::HTTP#use_ssl=]


