names=proxy_port,proxyport
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def proxy_port -> Integer|nil
### def proxyport -> Integer|nil

プロクシのポート番号を返します。

プロクシを使わない場合は nil を返します。

proxyport は時代遅れのメソッドです。

- **SEE** [m:Net::HTTP#proxy_port=], [m:Net::HTTP#proxy_address], [m:Net::HTTP.new]

