names=get
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTP.get(uri) -> String
### def Net::HTTP.get(host, path, port = 80) -> String

指定した対象に GET リクエストを送り、そのボディを文字列として返します。

対象の指定方法は [c:URI] で指定するか、
(host, path, port) で指定するかのいずれかです。

- **param** `uri` -- データの取得対象を [c:URI] で指定します。
- **param** `host` -- 接続先のホストを文字列で指定します。
- **param** `path` -- データの存在するパスを文字列で指定します。
- **param** `port` -- 接続するポートを整数で指定します。
- **SEE** [m:Net::HTTP#get]

