names=post_form
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTP.post_form(uri, params) -> Net::HTTPResponse

[c:URI] で指定した対象に フォームのデータを HTTP で
POST します。

送るデータは params に文字列から文字列への [c:Hash] として渡します。

- **param** `uri` -- POST する対象を [c:URI] で指定します。
- **param** `params` -- POST するデータです。

