names=proxy_use_ssl
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_use_ssl=3.4
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTP.proxy_use_ssl -> bool | nil

`self` が [m:Net::HTTP.Proxy] によって作成されたプロクシ用のクラスで、かつプロクシとの接続に SSL/TLS を使う場合に真を返します。

プロクシを使わない場合は nil を返します。

```ruby title="例"
require 'net/http'

proxy_class = Net::HTTP.Proxy('proxy.example.com', 8080, nil, nil, true)
proxy_class.proxy_use_ssl # => true
```

- **SEE** [m:Net::HTTP.Proxy], [m:Net::HTTP#proxy_use_ssl=]


