names=put
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=put=3.4
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTP.put(url, data, header = nil) -> Net::HTTPResponse

[c:URI] で指定した対象にデータを PUT し、そのレスポンスを [c:Net::HTTPResponse] として返します。

このメソッドは以下とほぼ同じです。

```ruby title="例"
require 'net/http'
Net::HTTP.start(url.hostname, url.port, use_ssl: url.scheme == 'https') {|http|
  http.put(url, data, header)
}
```

- **param** `url` -- PUT する対象を [c:URI] で指定します。
- **param** `data` -- PUT するデータを文字列で指定します。
- **param** `header` -- リクエストの HTTP ヘッダをハッシュで指定します。

```ruby title="例"
require 'net/http'

uri = URI('http://www.example.com/index.html')
Net::HTTP.put(uri, 'query=subject&target=ruby', 'content-type' => 'application/x-www-form-urlencoded')
```

- **SEE** [m:Net::HTTP#put], [c:Net::HTTP::Put]


