services:
  rurema:
    build:
      context: .
    volumes:
      - "./db:/home/rurema/db"
      - "./html/ja:/home/rurema/html/ja"
      - "./tool:/home/rurema/tool"
    command: "/bin/bash"
    profiles:
      - tools

  rurema-search:
    build:
      context: .
      dockerfile: Dockerfile.rurema-search
    volumes:
      - "./db:/home/rurema/db:ro"
      - "./tool:/home/rurema/tool:ro"
      - "groonga-database:/home/rurema/rurema-search/groonga-database"
      - "suggest:/home/rurema/rurema-search/var/lib/suggest"
      - "./repos/docs.ruby-lang.org/public:/usr/share/nginx/html:ro"
      - "./html/ja:/usr/share/nginx/html/ja:ro"
      - "./example/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "9000:80"

volumes:
  groonga-database:
  suggest:
