names=[],sym
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.jfEaAt/src/refm/api/src/dl/dl1/Handle

--- sym(func) -> DL::PtrData
--- [](func)  -> DL::PtrData
@todo

関数やグローバル変数 func へのポインタを取得し、
[[c:DL::PtrData]] オブジェクトとして返します。

@param func 得たいシンボルの名前を文字列で与えます。

@raise RuntimeError シンボルが見つからなかった時に発生します。

--- sym(func, type)    -> DL::Symbol
--- [](func, type)     -> DL::Symbol
@todo

関数 func へのポインタを取得し、
[[c:DL::Symbol]] オブジェクトとして返します。
type は型修飾子からなる文字列で関数のプロトタイプを示します。

@param func 得たい関数の名前を文字列で与えます。

@param type 関数のプロトタイプを文字列で指定します。

@raise RuntimeError シンボルが見つからなかった時に発生します。

[[c:DL]] の「Type Specifiers」の項も参照して下さい。

