names=post_form
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.jfEaAt/src/refm/api/src/net/http.rd

--- post_form(uri, params) -> Net::HTTPResponse
[[c:URI]] で指定した対象に フォームのデータを HTTP で 
POST します。

送るデータは params に文字列から文字列への [[c:Hash]] として
渡します。

@param uri POST する対象を [[c:URI]] で指定します。
@param params POST するデータです。


