names=+@,ptr
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ZtgaSH/src/refm/api/src/dl/dl2/CPtr

--- ptr   -> DL::CPtr
--- +@    -> DL::CPtr

自身の指す値を CPtr にして返します。
自身の指す値はポインタであると仮定します。
C 言語におけるポインタのポインタに対する間接参照 *p と同じです。 

この返り値には、free 関数がセットされていません。

例:

 require 'dl/import'
 
 s = 'abc'
 cptr = DL::CPtr[s]
 cref = cptr.ref
 p cref.to_s(4).unpack('l*')[0]  #=> 136121648
 p cptr.to_i                     #=> 136121648
 p cref.ptr.to_s                 #=> "abc"

