names=[]
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ZtgaSH/src/refm/api/src/dl/dl2/CPtr

--- [](offset)            -> Integer

自身の指すアドレスに offset バイトを足したメモリ領域の先頭を整数として返します。

@param offset 値を得たい領域のアドレスまでのオフセット
@raise DL::DLError self の保持するポインタが NULL である場合に発生します

例:

 require 'dl'
 
 s = 'abc'
 cptr  = DL::CPtr[s]
 p cptr[0]            #=> 97           
 p cptr[1]            #=> 98

--- [](offset, len)       -> String

自身の指すアドレスに offset バイトを足したメモリ領域の先頭 len バイトを複製し、
文字列として返します。

(self + offset).to_s(len) と同等です。
offset + len が自身のサイズより小さいかを検証しません。

@param offset 値を得たい領域の先頭のアドレスまでのオフセットを整数で与えます。

@param len 値を得たい領域のサイズを指定します。
@raise DL::DLError self の保持するポインタが NULL である場合に発生します

例:

 require 'dl'
 
 s = 'abc'
 cptr  = DL::CPtr[s]
 p cptr[0, 1]            #=> "a"
 p cptr[1, 2]            #=> "bc"

