names=delete
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:1899

--- delete(key) -> [String] | nil
key ヘッダフィールドを削除します。

@param key 削除するフィールド名
@return 取り除かれたフィールドの値を返します。
        key ヘッダフィールドが存在しなかった場合には
        nil を返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Get.new(uri.request_uri)
req.content_length = 10
req.content_length  # => 10
req.delete("Content-Length")  # => ["10"]
req.content_length  # => nil
//}

