names=each_capitalized_name
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:1949

--- each_capitalized_name {|name| .... } -> ()
保持しているヘッダ名を正規化
('x-my-header' -> 'X-My-Header') 
して、ブロックに渡します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Get.new(uri.request_uri)
req.each_capitalized_name { |key| puts key }

# => Accept-Encoding
# => Accept
# => User-Agent
//}

