names=proxy_pass
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:623

--- proxy_pass -> String|nil
プロクシ経由で接続し、さらにプロクシのユーザ認証を
する HTTP オブジェクトなら認証のパスワードを
を返します。

そうでないなら nil を返します。
@see [[m:Net::HTTP#proxy_pass=]], [[m:Net::HTTP#proxy_user]], [[m:Net::HTTP.new]]

