names=verify_depth
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:1453

--- verify_depth -> Integer
証明書チェイン上の検証する最大の深さを返します。

@see [[m:Net::HTTP#verify_depth=]], [[m:OpenSSL::SSL::SSLContext#verify_depth]]

