names=proxy_from_env=
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.xqkPhh/src/refm/api/src/net/http.rd

--- proxy_from_env=(boolean)

プロクシ情報を環境変数から得るかどうかを指定します。

[[m:Net::HTTP#start]] で接続する前に設定する必要があります。

@param boolean プロクシ情報を環境変数から得るかどうかを指定する真偽値

@see [[m:Net::HTTP#proxy_from_env?]] 


