names=keep_alive_timeout=
visibility=public
kind=defined

--- keep_alive_timeout=(seconds)
以前のリクエストで使ったコネクションの再利用(keep-alive)を許可する秒数を
設定します。

この秒数以内に同じホストに次のリクエストを送った場合、
ソケットを再利用します。

デフォルトは2(秒)です。これは一般的にサーバ側の keep-alive の秒数
が2秒である場合が多いからです。

@see [[m:Net::HTTP#keep_alive_timeout]]

