names=local_port
visibility=public
kind=defined

--- local_port -> nil | Integer | String
接続に用いるローカルポートを返します。

nil の場合システムが適当にローカルポートを
決めます。

デフォルトは nil です。

@see [[m:Net::HTTP#local_port=]], [[m:Net::HTTP#local_host]]

