names=local_port=
visibility=public
kind=defined

--- local_port=(port)
接続に用いるローカルポートを設定します。

nil の場合システムが適当にローカルポートを
決めます。

デフォルトは nil です。

@param port ローカルポート(数値、もしくはサービス名文字列)

//emlist[例][ruby]{
require 'net/http'

http = Net::HTTP.new("www.example.com")
http.local_host = "192.168.0.5"
http.local_port = "53043"

http.start do |h|
  p h.get("/").body
end
//}

@see [[m:Net::HTTP#local_port=]], [[m:Net::HTTP#local_host]]


@see [[m:Net::HTTP.new]]
