names=local_host
visibility=public
kind=defined

--- local_host -> String | nil

接続に用いるローカルホスト名を返します。

nil の場合システムが適当にローカルホストを
決めます。

デフォルトは nil です。


@see [[m:Net::HTTP#local_host=]], [[m:Net::HTTP#local_port]]

