names=open_timeout
visibility=public
kind=defined

--- open_timeout -> Integer|nil
接続時に待つ最大秒数を返します。

この秒数たってもコネクションが
開かなければ例外 [[c:Net::OpenTimeout]] を発生します。

デフォルトは60(秒)です。

@see [[m:Net::HTTP#read_timeout]], [[m:Net::HTTP#open_timeout=]]

