names=proxy_from_env?
visibility=public
kind=defined

--- proxy_from_env? -> bool

プロクシ情報を環境変数から得る場合に true を返します。

基本的に [[m:Net::HTTP.new]] や [[m:Net::HTTP.start]] の proxy_address
引数に :ENV を渡した場合に true になります。

環境変数 http_proxy が定義されていなくともこの値は true を返します。
その場合にはプロクシは利用されず直接サーバに接続します。

@see [[m:Net::HTTP#proxy_from_env=]] 

