names=proxy_from_env=
visibility=public
kind=defined

--- proxy_from_env=(boolean)

プロクシ情報を環境変数から得るかどうかを指定します。

[[m:Net::HTTP#start]] で接続する前に設定する必要があります。

@param boolean プロクシ情報を環境変数から得るかどうかを指定する真偽値

@see [[m:Net::HTTP#proxy_from_env?]] 


