names=proxy_user=
visibility=public
kind=defined

--- proxy_user=(user)
プロクシのユーザ認証のユーザ名を設定します。

[[m:Net::HTTP#start]] で接続する前に設定する必要があります。

@param user ユーザ名文字列
@see [[m:Net::HTTP#proxy_pass]], [[m:Net::HTTP#proxy_user]], [[m:Net::HTTP.new]]


