names=proxy_address=
visibility=public
kind=defined

--- proxy_address=(address)

プロクシのアドレス(ホスト名、IPアドレス)を指定します。

[[m:Net::HTTP#start]] で接続する前に設定する必要があります。

@param address プロクシのホスト名、もしくはIPアドレスを表す文字列

@see [[m:Net::HTTP#proxy_address=]], [[m:Net::HTTP#proxy_port]], [[m:Net::HTTP.new]]


