names=new
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPRequest.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTPRequest.new(path, initheader = nil) -> Net::HTTPRequest

HTTP リクエストオブジェクトを生成します。

initheader でリクエストヘッダを指定できます。
{ヘッダフィールド名(文字列)=>その中身(文字列)} という
[c:Hash] を用います。

- **param** `path` -- リクエストする path を文字列で与えます。
- **param** `initheader` -- リクエストヘッダをハッシュで指定します。






