names=CODE_TO_OBJ
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPResponse:192

--- CODE_TO_OBJ -> Hash

HTTP レスポンスステータスコードから対応するクラスへのハッシュです。

//emlist[][ruby]{
require 'net/http'
Net::HTTPResponse::CODE_TO_OBJ['404'] # => Net::HTTPNotFound
//}

