names=CODE_CLASS_TO_OBJ
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPResponse:182

--- CODE_CLASS_TO_OBJ -> Hash

HTTP レスポンスステータスコードの最初の数字からレスポンスのクラス(分類)を
あらわすクラスへのハッシュです。

//emlist[][ruby]{
require 'net/http'
Net::HTTPResponse::CODE_CLASS_TO_OBJ['3'] # => Net::HTTPRedirection
//}

