names=ciphers=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=ciphers=3d=1.9.3
until_by_name=

### def ciphers=(ciphers)

利用可能な共通鍵暗号を設定します。

[m:OpenSSL::SSL::SSLContext#ciphers=] と同じ形式で設定します。詳しくはそちらを参照してください。

- **param** `ciphers` -- 利用可能にする共通鍵暗号の種類
- **SEE** [m:Net::HTTP#ciphers]

