names=continue_timeout=
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:807

--- continue_timeout=(seconds)
「100 Continue」レスポンスを待つ秒数を指定します。

この秒数待ってもレスポンスが来ない場合は
リクエストボディを送信します。

デフォルトは nil (待たない)です。

@param seconds 秒数
@see [[m:Net::HTTP#continue_timeout]]

