names=local_port=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=local_port=3d=2.0.0
until_by_name=
rbs_sig=(uninitialized)

### def local_port=(port)

接続に用いるローカルポートを設定します。

nil の場合システムが適当にローカルポートを決めます。

デフォルトは nil です。

- **param** `port` -- ローカルポート(数値、もしくはサービス名文字列)

```ruby title="例"
require 'net/http'

http = Net::HTTP.new("www.example.com")
http.local_host = "192.168.0.5"
http.local_port = "53043"

http.start do |h|
  p h.get("/").body
end
```

- **SEE** [m:Net::HTTP#local_port=], [m:Net::HTTP#local_host]

- **SEE** [m:Net::HTTP.new]

