names=min_version,min_version=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=min_version=2.5.0,min_version=3d=2.5.0
until_by_name=
rbs_sig=(uninitialized)

### def min_version -> Integer | Symbol | nil
{: since="2.5.0"}
### def min_version=(version)
{: since="2.5.0"}

利用する SSL/TLS のバージョンの下限を取得・設定します。

デフォルトは nil です。指定できる値は [m:OpenSSL::SSL::SSLContext#min_version=] と同じです。

- **param** `version` -- 利用する SSL/TLS のバージョンの下限
- **SEE** [m:Net::HTTP#max_version], [m:Net::HTTP#ssl_version=]




