names=default_port,http_default_port
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def http_default_port -> Integer
### def default_port -> Integer

HTTP のデフォルトポート (80) を返します。

