names=message,msg
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def message -> String
### def msg -> String

HTTP サーバがリザルトコードに付加して返すメッセージです。
例えば 'Not Found' などです。

msg は obsolete です。使わないでください。

```ruby title="例"
require 'net/http'

uri = "http://www.example.com/index.html"
response = Net::HTTP.get_response(URI.parse(uri))
p response.message # => "OK"
```

