names=read_timeout=
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:727

--- read_timeout=(seconds)

読みこみ([[man:read(2)]]) 一回でブロックしてよい最大秒数を
設定します。

この秒数たっても読みこめなければ例外 [[c:Net::ReadTimeout]]
を発生します。

nilを設定するとタイムアウトしなくなります。

このタイムアウト秒数はサーバとやりとりするメソッドで有効です。

デフォルトは 60 (秒)です。

@param second 待つ秒数を指定します。
@see [[m:Net::HTTP#open_timeout]], [[m:Net::HTTP#read_timeout]]



