names=active?,started?
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md

### def started? -> bool
### def active? -> bool

HTTP セッションが開始されていたら真を返します。

active? は時代遅れのメソッドです。

