names=ca_file
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def ca_file -> String | nil

信頼する CA 証明書ファイルのパスを返します。

- **SEE** [m:Net::HTTP#ca_file=], [m:OpenSSL::SSL::SSLContext#ca_file]

