names=ignore_eof,ignore_eof=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=ignore_eof=3.2,ignore_eof=3d=3.2
until_by_name=
rbs_sig=(uninitialized)

### def ignore_eof -> bool
### def ignore_eof=(bool)

`Content-Length:` ヘッダフィールドが指定されたレスポンスボディを読み込む際に、EOF (End Of File) を無視するかどうかを取得・設定します。

デフォルトは true です。

- **param** `bool` -- EOF を無視するかどうかを真偽値で指定します。


