names=max_retries=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=max_retries=3d=3.0
until_by_name=

### def max_retries=(times)

冪等なリクエストが [c:Net::ReadTimeout]、[c:IOError]、[c:EOFError]、
[c:Errno::ECONNRESET]、[c:Errno::ECONNABORTED]、[c:Errno::EPIPE]、
[c:OpenSSL::SSL::SSLError]、[c:Timeout::Error] のいずれかで失敗した場合に
再試行する最大回数を設定します。

デフォルトは 1 です。

- **param** `times` -- 再試行する最大回数を 0 以上の整数で指定します。
             負の値を指定した場合は [c:ArgumentError] が発生します。

```ruby title="例"
http = Net::HTTP.new(hostname)
http.max_retries = 2   # => 2
http.max_retries       # => 2
```

- **SEE** [m:Net::HTTP#max_retries]

