names=max_version,max_version=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=max_version=3.0,max_version=3d=3.0
until_by_name=
rbs_sig=(uninitialized)

### def max_version -> Integer | Symbol | nil
### def max_version=(version)

利用する SSL/TLS のバージョンの上限を取得・設定します。

デフォルトは nil です。指定できる値は [m:OpenSSL::SSL::SSLContext#max_version=] と同じです。

- **param** `version` -- 利用する SSL/TLS のバージョンの上限
- **SEE** [m:Net::HTTP#min_version], [m:Net::HTTP#ssl_version=]

