names=proxy_user=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_user=3d=2.0.0
until_by_name=
rbs_sig=(uninitialized)

### def proxy_user=(user)

プロクシのユーザ認証のユーザ名を設定します。

[m:Net::HTTP#start] で接続する前に設定する必要があります。

- **param** `user` -- ユーザ名文字列
- **SEE** [m:Net::HTTP#proxy_pass], [m:Net::HTTP#proxy_user], [m:Net::HTTP.new]

