names=proxy_user
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:640

--- proxy_user -> String|nil
プロクシ経由で接続し、さらにプロクシのユーザ認証を
する HTTP オブジェクトなら認証のユーザ名を
を返します。

そうでないなら nil を返します。

@see [[m:Net::HTTP#proxy_pass]], [[m:Net::HTTP#proxy_user=]], [[m:Net::HTTP.new]]


