names=proxy_pass=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_pass=3d=2.0.0
until_by_name=

### def proxy_pass=(pass)
プロクシのユーザ認証のパスワードを設定します。

[m:Net::HTTP#start] で接続する前に設定する必要があります。

- **param** `pass` -- パスワード文字列
- **SEE** [m:Net::HTTP#proxy_pass], [m:Net::HTTP#proxy_user], [m:Net::HTTP.new]


