names=ssl_version
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=ssl_version=1.9.3
until_by_name=

### def ssl_version -> String | Symbol | nil
利用するプロトコルの種類を返します。

- **SEE** [m:Net::HTTP#ssl_version=]

