names=verify_depth
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def verify_depth -> Integer

証明書チェイン上の検証する最大の深さを返します。

- **SEE** [m:Net::HTTP#verify_depth=], [m:OpenSSL::SSL::SSLContext#verify_depth]

