names=post
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=post=2.4.0
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTP.post(url, data, header = nil) -> Net::HTTPResponse
{: since="2.4.0"}

[c:URI] で指定した対象にデータを POST し、そのレスポンスを [c:Net::HTTPResponse] として返します。

このメソッドは以下とほぼ同じです。

```ruby title="例"
require 'net/http'
Net::HTTP.start(url.hostname, url.port, use_ssl: url.scheme == 'https') {|http|
  http.post(url, data, header)
}
```

- **param** `url` -- POST する対象を [c:URI] で指定します。
- **param** `data` -- POST するデータを文字列で指定します。
- **param** `header` -- リクエストの HTTP ヘッダをハッシュで指定します。

```ruby title="例"
require 'net/http'

uri = URI('http://www.example.com/index.html')
Net::HTTP.post(uri, 'query=subject&target=ruby', 'content-type' => 'application/x-www-form-urlencoded')
```

- **SEE** [m:Net::HTTP#post], [c:Net::HTTP::Post]

