names=body_encoding,body_encoding=
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=body_encoding=3.2,body_encoding=3d=3.2
until_by_name=
rbs_sig=(uninitialized)

### def body_encoding -> Encoding | false
### def body_encoding=(value)

エンティティボディを読み込む際に使うエンコーディングを取得・設定します。

デフォルトは false で、この場合ボディの内容からエンコーディングが推測されます。

value には [c:Encoding] オブジェクト、またはエンコーディング名を表す文字列を指定できます。文字列を指定した場合は [m:Encoding.find] を使って [c:Encoding] オブジェクトに変換されます。

- **param** `value` -- 使用するエンコーディング ([c:Encoding] オブジェクトまたはその名前を表す文字列)

```ruby title="例"
require 'net/http'

http = Net::HTTP.new('www.example.com')
req = Net::HTTP::Get.new('/')
http.request(req) do |res|
  res.body_encoding = "UTF-8"
  p res.body.encoding # => #<Encoding:UTF-8>
end
```


