names=decode_content,decode_content=
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=decode_content=3.0,decode_content=3d=3.0
until_by_name=
rbs_sig=(uninitialized)

### def decode_content -> bool
### def decode_content=(bool)

エンティティボディの `Content-Encoding:` を自動的に展開するかどうかを取得・設定します。

ユーザがリクエストヘッダフィールド `Accept-Encoding:` を明示的に設定・削除していなかった場合に、自動的に真が設定されます。真の場合、[m:Net::HTTPResponse#read_body] などでボディを読み込む際に、レスポンスの `Content-Encoding:` が gzip や deflate であればボディを透過的に展開します。

- **param** `bool` -- `Content-Encoding:` を自動的に展開するかどうかを真偽値で指定します。
- **SEE** [m:Net::HTTPGenericRequest#decode_content]

