names=uri
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=uri=2.0.0
until_by_name=
rbs_sig=(uninitialized)

### def uri -> URI | nil
{: since="2.0.0"}

このレスポンスの取得に使われた [c:URI] オブジェクトを返します。

リクエストの生成に URI オブジェクトを使わなかった場合は nil を返します。

```ruby title="例"
require 'net/http'

uri = URI('http://www.example.com/index.html')
response = Net::HTTP.get_response(uri)
p response.uri # => #<URI::HTTP http://www.example.com/index.html>
```

- **SEE** [m:Net::HTTPGenericRequest#uri]

