names=body_permitted?
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTPResponse.body_permitted? -> bool

エンティティボディを含むことが許されているレスポンスクラスならば真を、そうでなければ偽を返します。

```ruby title="例"
require 'net/http'

p Net::HTTPSuccess.body_permitted?   # => true
p Net::HTTPNotModified.body_permitted? # => false
```

