names=body_permitted?
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPResponse:9

--- body_permitted? -> bool
エンティティボディを含むことが許されているレスポンスクラス
ならば真を、そうでなければ偽を返します。

//emlist[例][ruby]{
require 'net/http'

Net::HTTPSuccess.body_permitted?     # => true
Net::HTTPNotModified.body_permitted? # => false
//}

