names=body
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPGenericRequest.md

### def body -> String
サーバに送るリクエストのエンティティボディを返します。

```ruby title="例"
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Post.new(uri.request_uri)
req.body = "Test Post Data"
req.body # => "Test Post Data"
```

- **SEE** [m:Net::HTTPGenericRequest#body=]

