names=cert
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def cert -> OpenSSL::X509::Certificate | nil

クライアント証明書を返します。

- **SEE** [m:Net::HTTP#cert=], [m:OpenSSL::SSL::SSLContext#cert]

