names=ipaddr,ipaddr=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=ipaddr=3.0,ipaddr=3d=3.0
until_by_name=
rbs_sig=(uninitialized)

### def ipaddr -> String | nil
### def ipaddr=(addr)

接続先の IP アドレスを取得・設定します。

セッションが開始されていない場合は、`ipaddr=` で設定した値 (未設定なら nil) を返します。セッションが開始されている場合は、実際に接続したソケットの IP アドレスを返します。

`ipaddr=` はセッションが開始された後には設定できません。

- **param** `addr` -- 接続先の IP アドレスを文字列で指定します。
- **raise** `IOError` -- セッション開始後に `ipaddr=` で値を変更しようとすると発生します。

```ruby title="例"
require 'net/http'

http = Net::HTTP.new('www.example.com')
http.ipaddr         # => nil
http.ipaddr = '172.67.155.76'
http.ipaddr         # => "172.67.155.76"
```

- **SEE** [m:Net::HTTP.new]

