names=local_host=
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:510

--- local_host=(host)

接続に用いるローカルホスト名を指定します。

nil の場合システムが適当にローカルホストを
決めます。

デフォルトは nil です。

@param host ホスト名、もしくはアドレスを示す文字列

//emlist[例][ruby]{
require 'net/http'

http = Net::HTTP.new("www.example.com")
http.local_host = "192.168.0.5"
http.local_port = "53043"

http.start do |h|
  p h.get("/").body
end
//}

@see [[m:Net::HTTP#local_host=]], [[m:Net::HTTP#local_port]]

