names=local_host
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=local_host=2.0.0
until_by_name=

### def local_host -> String | nil

接続に用いるローカルホスト名を返します。

nil の場合システムが適当にローカルホストを
決めます。

デフォルトは nil です。

- **SEE** [m:Net::HTTP#local_host=], [m:Net::HTTP#local_port]

