names=proppatch
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def proppatch(path, body, initheader = nil) -> Net::HTTPResponse

サーバの path に PROPPATCH リクエストをヘッダを initheader, ボディを body として送ります。

レスポンスを [c:Net::HTTPResponse] のオブジェクトで返します。

- **param** `path` -- リクエストを送るパスを文字列で与えます。
- **param** `body` -- リクエストのボディを文字列で与えます。
- **param** `initheader` -- リクエストのヘッダを「文字列=>文字列」のハッシュで与えます。

- **SEE** [c:Net::HTTP::Proppatch]

