names=ssl_timeout
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def ssl_timeout -> Integer | nil
SSL/TLS のタイムアウト秒数を返します。

設定されていない場合は nil を返します。

- **SEE** [m:Net::HTTP#ssl_timeout=],
     [m:OpenSSL::SSL::SSLContext#ssl_timeout]

