names=content_range
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:1862

--- content_range -> Range|nil

Content-Range: ヘッダフィールドの値を Range で返します。
Range の表わす長さは [[m:Net::HTTPHeader#range_length]] で得られます。

ヘッダが設定されていない場合には nil を返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Get.new(uri.request_uri)
req.content_range      # => nil
req['Content-Range'] = "bytes 0-499/1234"
req.content_range      # => 0..499
//}

