names=body=
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPRequest:42

--- body=(body)

サーバに送るリクエストのエンティティボディを文字列で設定します。

@param body 設定するボディを文字列で与えます。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Post.new(uri.request_uri)
req.body = "Test Post Data" # => "Test Post Data"
//}

@see [[m:Net::HTTPGenericRequest#body]]


