names=response_body_permitted?
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPRequest:125

--- response_body_permitted? -> bool

サーバからのレスポンスにエンティティボディを含むことが許されている
HTTP メソッド (GET, POST など)の場合真を返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
post = Net::HTTP::Post.new(uri.request_uri)
post.response_body_permitted?   # => true

head = Net::HTTP::Head.new(uri.request_uri)
head.response_body_permitted?   # => false
//}

