names=body=
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=body=3d=3.0
until_by_name=
rbs_sig=(uninitialized)

### def body=(value)

エンティティボディを value に設定します。

- **param** `value` -- 設定するボディを文字列で指定します。

```ruby title="例"
require 'net/http'

uri = URI('http://www.example.com/index.html')
response = Net::HTTP.get_response(uri)
response.body = 'dummy'
p response.body # => "dummy"
```

- **SEE** [m:Net::HTTPResponse#body], [m:Net::HTTPResponse#read_body]

