names=ignore_eof,ignore_eof=
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=ignore_eof=3.2,ignore_eof=3d=3.2
until_by_name=
rbs_sig=(uninitialized)

### def ignore_eof -> bool
### def ignore_eof=(bool)

`Content-Length:` ヘッダフィールドが指定されたボディを読み込む際に、EOF (End Of File) を無視するかどうかを取得・設定します。

- **param** `bool` -- EOF を無視するかどうかを真偽値で指定します。

```ruby title="例"
require 'net/http'

uri = URI('http://www.example.com/index.html')
response = Net::HTTP.get_response(uri)
response.ignore_eof = false
p response.ignore_eof # => false
```

- **SEE** [m:Net::HTTP#ignore_eof]


