names=[],to_ptr
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.Phg2K5/src/refm/api/src/dl/dl2/CPtr

--- [](val)       -> DL::CPtr
--- to_ptr(val)   -> DL::CPtr

与えられた val と関連した CPtr オブジェクトを生成して返します。

val が文字列の場合は文字列が格納されているメモリ領域を指す CPtr オブジェクトを返します。
IO オブジェクトの場合は FILE ポインタを表す CPtr オブジェクトを返します。
val に to_ptr メソッドが定義されている場合は、val.to_ptr を呼びます。
上以外の場合は、整数に変換しそれをアドレスとする CPtr オブジェクトを返します。


@param val Ruby オブジェクトを指定します。

@raise DL::DLError to_ptr の返り値が CPtr オブジェクトでない場合に発生します
@raise TypeError 上記のいずれの変換も不可能であった場合に発生します

例:

 require 'dl'
 s = "abc"
 p DL::CPtr[s].to_i                 #=> 136186388
 p [s].pack('p*').unpack('l!*')[0]  #=> 136186388

