names=malloc
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.Phg2K5/src/refm/api/src/dl/dl2/CPtr

--- malloc(size, free = nil)   -> DL::CPtr

与えられた長さ size のメモリ領域を確保し、それを表す CPtr オブジェクトを生成して返します。

@param size 確保したいメモリ領域のサイズを整数で指定します。

@param free GC 時に呼ばれる CPtr オブジェクトの free 関数を [[c:DL::CFunc]] オブジェクトか整数で指定します。

