names=CODE_TO_OBJ
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=CODE_TO_OBJ=2.5.0
until_by_name=
rbs_sig=(uninitialized)

### const CODE_TO_OBJ -> Hash

HTTP レスポンスステータスコードから対応するクラスへのハッシュです。

```ruby
require 'net/http'
p Net::HTTPResponse::CODE_TO_OBJ['404'] # => Net::HTTPNotFound
```

