names=CODE_CLASS_TO_OBJ
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=CODE_CLASS_TO_OBJ=2.5.0
until_by_name=

### const CODE_CLASS_TO_OBJ -> Hash

HTTP レスポンスステータスコードの最初の数字からレスポンスのクラス(分類)を
あらわすクラスへのハッシュです。

```ruby
require 'net/http'
p Net::HTTPResponse::CODE_CLASS_TO_OBJ['3'] # => Net::HTTPRedirection
```

