names=body,entity
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPResponse.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def body -> String | () | nil
### def entity -> String | () | nil

エンティティボディを返します。

レスポンスにボディがない場合には nil を返します。

[m:Net::HTTPResponse#read_body] をブロック付きで呼んだ場合にはこのメソッドはNet::ReadAdapter のインスタンスを返しますが、これは使わないでください。

entity は obsolete です。

```ruby title="例"
require 'net/http'

uri = "http://www.example.com/index.html"
response = Net::HTTP.get_response(URI.parse(uri))
p response.body[0..10] # => "<!doctype h"
```

