names=open_timeout
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def open_timeout -> Integer|nil

接続時に待つ最大秒数を返します。

この秒数たってもコネクションが開かなければ例外 [c:Net::OpenTimeout] を発生します。

デフォルトは 60 (秒)です。

- **SEE** [m:Net::HTTP#read_timeout], [m:Net::HTTP#open_timeout=]

