names=proxy_address=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_address=3d=2.0.0
until_by_name=

### def proxy_address=(address)

プロクシのアドレス(ホスト名、IPアドレス)を指定します。

[m:Net::HTTP#start] で接続する前に設定する必要があります。

- **param** `address` -- プロクシのホスト名、もしくはIPアドレスを表す文字列

- **SEE** [m:Net::HTTP#proxy_address=], [m:Net::HTTP#proxy_port], [m:Net::HTTP.new]

