names=response_body_encoding,response_body_encoding=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=response_body_encoding=3.2,response_body_encoding=3d=3.2
until_by_name=
rbs_sig=(uninitialized)

### def response_body_encoding -> Encoding | false
### def response_body_encoding=(value)

レスポンスボディに使うエンコーディングを取得・設定します。

デフォルトは false で、この場合エンコーディングは強制されません。

value には [c:Encoding] オブジェクト、エンコーディング名の文字列、エンコーディング名のエイリアスの文字列のいずれかを指定できます。文字列を指定した場合は [m:Encoding.find] を使って [c:Encoding] オブジェクトに変換されます。詳しくは [c:Encoding] を見てください。

- **param** `value` -- 使用するエンコーディング ([c:Encoding] オブジェクトまたはその名前を表す文字列)

```ruby title="例"
require 'net/http'

http = Net::HTTP.new('www.example.com')
p http.response_body_encoding # => false
http.response_body_encoding = Encoding::US_ASCII
p http.response_body_encoding # => #<Encoding:US-ASCII>
http.response_body_encoding = 'US-ASCII'
p http.response_body_encoding # => #<Encoding:US-ASCII>
http.response_body_encoding = 'ASCII'
p http.response_body_encoding # => #<Encoding:US-ASCII>
```


