names=request_query
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=request_query=4.1
until_by_name=
rbs_sig=(uninitialized)

### def request_query(path, data, initheader = nil) -> Net::HTTPResponse
### def request_query(path, data, initheader = nil) {|response| .... } -> Net::HTTPResponse

サーバ上の path にあるエンティティに対し文字列 data を QUERY メソッドで送ります。

返り値は [c:Net::HTTPResponse] のインスタンスです。

ブロックとともに呼び出されたときは、エンティティボディをソケットから読み出す前に、接続を維持した状態で [c:Net::HTTPResponse] オブジェクトをブロックに渡します。

- **param** `path` -- リクエストを送るパスを文字列で指定します。
- **param** `data` -- 送るデータを文字列で指定します。
- **param** `initheader` -- リクエストの HTTP ヘッダをハッシュで指定します。

- **SEE** [m:Net::HTTP#query], [m:Net::HTTPResponse#read_body]


