names=write_timeout
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=write_timeout=2.6.0
until_by_name=
rbs_sig=(uninitialized)

### def write_timeout -> Numeric|nil

書き込み([man:write(2)]) 一回でブロックしてよい最大秒数を返します。

この秒数たっても書き込めなければ例外 [c:Net::WriteTimeout]
を発生します。

Windows では Net::WriteTimeout は発生しません。

デフォルトは 60 (秒)です。

- **SEE** [m:Net::HTTP#open_timeout], [m:Net::HTTP#read_timeout], [m:Net::HTTP#write_timeout=]

