names=verify_callback=
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ryNQ5k/src/refm/api/src/net/http.rd

--- verify_callback=(proc)
検証をフィルタするコールバックを設定します。

詳しくは [[m:OpenSSL::X509::Store#verify_callback=]] や
[[m:OpenSSL::SSL::SSLContext#verify_callback=]] を見てください。

@param proc 設定する [[c:Proc]] オブジェクト
@see [[m:Net::HTTP#verify_callback]],
     [[m:OpenSSL::X509::Store#verify_callback=]],
     [[m:OpenSSL::SSL::SSLContext#verify_callback=]]

