names=path
visibility=public
kind=defined
source_location=manual/api/net/Net__HTTPGenericRequest.md

### def path -> String

リクエストする path を文字列で返します。

```ruby title="例"
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
req = Net::HTTP::Get.new(uri.request_uri)
req.path # => "/index.html"
```

