names=calltype,calltype=
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ZtgaSH/src/refm/api/src/dl/dl2/CFunc

--- calltype         -> Symbol
--- calltype=(sym)

自身の呼出規約を表すアクセサです。
サポートされている規約は :cdecl と :stdcall です。

@param sym 自身の呼出規約を Symbol オブジェクトで指定します。

@see [[url:http://ja.wikipedia.org/wiki/%E5%91%BC%E5%87%BA%E8%A6%8F%E7%B4%84]]

