names=new
visibility=public
kind=defined
source_location=/tmp/claude-1000/-home-debian-rurema/3717a77b-67d6-4a40-b15e-a41ca141ab34/scratchpad/frozen.ZtgaSH/src/refm/api/src/net/Net__HTTPRequest

--- new(path, initheader = nil) -> Net::HTTPRequest
HTTP リクエストオブジェクトを生成します。

initheader でリクエストヘッダを指定することができます。
{ヘッダフィールド名(文字列)=>その中身(文字列)} という
[[c:Hash]] を用います。

@param path リクエストする path を文字列で与えます。
@param initheader リクエストヘッダをハッシュで指定します。





