names=extra_chain_cert,extra_chain_cert=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=extra_chain_cert=3.0,extra_chain_cert=3d=3.0
until_by_name=
rbs_sig=(uninitialized)

### def extra_chain_cert -> [OpenSSL::X509::Certificate] | nil
### def extra_chain_cert=(certificates)

証明書チェインに追加する、自分自身を証明する証明書からルート CA までの証明書 (クライアント証明書自体は除く) を取得・設定します。

デフォルトは nil です。

詳しくは [m:OpenSSL::SSL::SSLContext#extra_chain_cert], [m:OpenSSL::SSL::SSLContext#extra_chain_cert=] を見てください。

- **param** `certificates` -- 証明書チェインに追加する [c:OpenSSL::X509::Certificate] の配列
- **SEE** [m:OpenSSL::SSL::SSLContext#extra_chain_cert], [m:OpenSSL::SSL::SSLContext#extra_chain_cert=]

