names=max_retries
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=max_retries=3.0
until_by_name=

### def max_retries -> Integer
冪等なリクエストが失敗した場合に再試行する最大回数を返します。

デフォルトは 1 です。

- **SEE** [m:Net::HTTP#max_retries=]

