names=proxy_port=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_port=3d=2.0.0
until_by_name=

### def proxy_port=(port)

プロクシのポート番号を設定します。

[m:Net::HTTP#start] で接続する前に設定する必要があります。

- **param** `port` -- ポート番号(整数、文字列)
- **SEE** [m:Net::HTTP#proxy_port], [m:Net::HTTP#proxy_address], [m:Net::HTTP.new]

