names=proxy_address,proxyaddr
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def proxy_address -> String|nil
### def proxyaddr -> String|nil

プロクシ経由で接続する HTTP オブジェクトならプロクシのアドレスを返します。

そうでないなら nil を返します。

proxyaddr は時代遅れのメソッドです。

- **SEE** [m:Net::HTTP#proxy_address=], [m:Net::HTTP#proxy_port], [m:Net::HTTP.new]

