names=proxy_uri
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=proxy_uri=2.0.0
until_by_name=
rbs_sig=(uninitialized)

### def proxy_uri -> String|nil

このメソッドは内部用なので使わないでください。

環境変数 http_proxy から得られるプロクシの URI を返します。

