names=verify_hostname,verify_hostname=
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=verify_hostname=3.0,verify_hostname=3d=3.0
until_by_name=
rbs_sig=(uninitialized)

### def verify_hostname -> bool | nil
### def verify_hostname=(bool)

証明書がホスト名に対して有効かどうかを検証するかどうかを取得・設定します。

詳しくは [m:OpenSSL::SSL::SSLContext#verify_hostname] を見てください。

デフォルトは nil です。

- **param** `bool` -- ホスト名の検証を行うかどうかを真偽値で指定します。
- **SEE** [m:Net::HTTP#verify_mode], [m:Net::HTTP#verify_mode=]

