names=verify_callback
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def verify_callback -> Proc

自身に設定されている検証をフィルタするコールバックを返します。

デフォルトのコールバックが設定されている場合には nil を返します。

- **SEE** [m:Net::HTTP#verify_callback=],
     [m:OpenSSL::X509::Store#verify_callback],
     [m:OpenSSL::SSL::SSLContext#verify_callback]

