names=is_version_1_1?,version_1_1?
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def version_1_1? -> false
### def is_version_1_1? -> false
何もしません。互換性のために残されており、常に false を返します。

- **SEE** [m:Net::HTTP.version_1_2], [m:Net::HTTP.version_1_2?]


