names=proxy_user
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def Net::HTTP.proxy_user -> String|nil

自身が ([m:Net::HTTP.Proxy] によって作成された)
プロクシ用のクラスで、かつプロクシの認証を利用する場合はプロクシ認証のユーザ名を返します。

そうでなければ nil を返します。

- **SEE** [m:Net::HTTP.Proxy]


