names=ca_path
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md

### def ca_path -> String | nil
信頼する CA 証明書ファイルが存在するディレクトリを設定します。

- **SEE** [m:Net::HTTP#ca_path=], [m:OpenSSL::SSL::SSLContext#ca_path]

