names=key
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=

### def key -> OpenSSL::PKey::PKey | nil
クライアント証明書の秘密鍵を返します。

- **SEE** [m:Net::HTTP#key=], [m:OpenSSL::SSL::SSLContext#key]

