names=keep_alive_timeout
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=keep_alive_timeout=2.0.0
until_by_name=

### def keep_alive_timeout -> Integer

以前のリクエストで使ったコネクションの再利用(keep-alive)を許可する秒数を返します。

デフォルトは2(秒)です。

- **SEE** [m:Net::HTTP#keep_alive_timeout=]

