names=ssl_version=
visibility=public
kind=defined
source_location=refm/api/src/net/http.rd:1488

--- ssl_version=(ver)
利用するプロトコルの種類を指定します。

[[m:OpenSSL::SSL::SSLContext.new]] で指定できるものと同じです。

@param ver 利用するプロトコルの種類(文字列 or シンボル)
@see [[m:Net::HTTP#ssl_version]], [[m:OpenSSL::SSL::SSLContext#ssl_version=]]


