names=proxy_class?
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTP.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def Net::HTTP.proxy_class? -> bool

自身が ([m:Net::HTTP.Proxy] によって作成された) プロクシ用のクラスならば真を返し、そうでなければ偽を返します。

- **SEE** [m:Net::HTTP.Proxy]

