names=body,entity
visibility=public
kind=defined
source_location=refm/api/src/net/Net__HTTPResponse:109

--- body -> String | () | nil
--- entity -> String | () | nil

エンティティボディを返します。

レスポンスにボディがない場合には nil を返します。

[[m:Net::HTTPResponse#read_body]] をブロック付きで呼んだ場合には
このメソッドはNet::ReadAdapter のインスタンスを返しますが、
これは使わないでください。

entity は obsolete です。

//emlist[例][ruby]{
require 'net/http'

uri = "http://www.example.com/index.html"
response = Net::HTTP.get_response(URI.parse(uri))
response.body[0..10] # => "<!doctype h"
//}

