names=connection_close?
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTPHeader.md
since_by_name=connection_close=3f=3.0
until_by_name=
rbs_sig=(uninitialized)

### def connection_close? -> bool

`Connection:` ヘッダフィールド (プロクシ経由の場合は `Proxy-Connection:` ヘッダフィールド) が `close` を指定しているかどうかを返します。

```ruby title="例"
require 'net/http'

uri = URI('http://www.example.com/index.html')
req = Net::HTTP::Get.new(uri)
p req.connection_close? # => false
req['Connection'] = 'close'
p req.connection_close? # => true
```

- **SEE** [m:Net::HTTPHeader#connection_keep_alive?]

