names=length,size
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTPHeader.md
since_by_name=
until_by_name=
rbs_sig=(uninitialized)

### def size -> Integer
### def length -> Integer

このメソッドは obsolete です。

ヘッダフィールドの数を返します。


