names=type_params
visibility=public
kind=defined
source_location=manual/api/net/http/Net__HTTPHeader.md
since_by_name=
until_by_name=

### def type_params -> Hash

Content-Type のパラメータを {"charset" => "iso-2022-jp"}
という形の [c:Hash] で返します。

Content-Type: ヘッダフィールドが存在しない場合には空のハッシュを返します。

```ruby title="例"
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
res = Net::HTTP.get_response(uri)
p res.type_params # => {"charset"=>"UTF-8"}
```

