names=content_type
visibility=public
kind=defined

--- content_type -> String|nil
"text/html" のような Content-Type を表す
文字列を返します。

Content-Type: ヘッダフィールドが存在しない場合には nil を返します。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/comments.cgi?post=comment')
req = Net::HTTP::Post.new(uri.request_uri)
req.content_type  # => nil
req.content_type = 'multipart/form-data'
req.content_type  # => "multipart/form-data"
//}

