names=key?
visibility=public
kind=defined

--- key?(key) -> bool
key というヘッダフィールドがあれば真を返します。
key は大文字小文字を区別しません。

@param key 探すヘッダフィールド名を文字列で与えます。

//emlist[例][ruby]{
require 'net/http'

uri = URI.parse('http://www.example.com/index.html')
res = Net::HTTP.get_response(uri)
res.key?('content-type')     # => true
res.key?('nonexist-header')  # => false
//}

